export interface Vehicles{
    vehicleName: string,
    vehicleNumber: string,
    serviceType: string,
    type: string
    image: Array<string>,
    colour: string,
    fuel: string,
    numofseats: number,
    hubName: string,
    mileage: number,
    fairPrice: number,
    fairKm: number,
    status: boolean,
    specification: Array<string>,
    vehicleValidate: Date,
    documents: Array<string>,
    singleimage :string,
    subimages:Array<string>,
    vehicleValidityDate:string,
}